### ISSUE TITLE
Broken dependency in ed25519-signature-2018

### ISSUE THREAD

**Issue by rado0x54** [transmute-industries/verifiable-data#75]
`"@transmute/credentials-context": "^0.7.0-unstable.6"` should be a dependency and **not** a devDependency of `@transmute/ed25519-signature-2018"`

```
    Cannot find module '@transmute/credentials-context' from 'node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js'

    Require stack:
      node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js
      node_modules/@transmute/ed25519-signature-2018/dist/index.js
      packages/credential-w3c/src/ld-credential-module.ts
      packages/credential-w3c/src/index.ts
      __tests__/localAgent.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:311:11)
      at Object.<anonymous> (node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:12:12)
```
when only using `"@transmute/ed25519-signature-2018": "^0.7.0-unstable.6",` in package.json.

**Comment by vongohren** [comment]
Im hitting this aswell!

**Comment by AlexMesser** [comment]
same issue with `"@transmute/json-web-signature": "^0.7.0-unstable.50"`

```
Cannot find module 'jose' from 'packages/sdk/vc/node_modules/@transmute/jose-ld/dist/jose-ld.cjs.development.js'

    Require stack:
      packages/sdk/vc/node_modules/@transmute/jose-ld/dist/jose-ld.cjs.development.js
      packages/sdk/vc/node_modules/@transmute/jose-ld/dist/index.js
      packages/sdk/vc/node_modules/@transmute/json-web-signature/dist/json-web-signature.cjs.development.js
      packages/sdk/vc/node_modules/@transmute/json-web-signature/dist/index.js
      packages/sdk/vc/src/vc-manager.ts
      packages/sdk/vc/test/vc-manager.test.ts
```

**Comment by OR13** [comment]
we are not supporting these linked data suites moving forward, see https://github.com/transmute-industries/did-transmute and the new vc-jwt formats
